# Generated by Django 6.0.4 on 2026-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_department_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
